---
- name: Package install with loop
  hosts: all
  become: true
  gather_facts: false
  vars:
    php_modules:
      - php-mysql
      - php-pdo
      - php-xml

  tasks:
    - name: Installing php packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      loop: "{{ php_modules }}"
