---
- hosts: all
  gather_facts: false

  tasks:

  - name: Simulate long running op (15 sec), wait for up to 45 sec, poll every 5 sec
    ansible.builtin.command: /bin/sleep 15
    async: 45
    poll: 1

  - name: Simulate long running op (15 sec), wait for up to 2 sec, poll every 1 sec
    ansible.builtin.command: /bin/sleep 15
    async: 20
    poll: 2
