---
- hosts: all
  gather_facts: false
  connection: local

  tasks:
    - name: Run an async task
      ansible.builtin.command: sleep 50
      async: 60
      poll: 0
      register: sleeper

    - name: Check on an async task
      async_status:
        jid: "{{ sleeper.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 10