---
- hosts: all
  gather_facts: false

  vars:
    username: king

  vars_prompt:

    - name: username
      prompt: What is your username?
      private: false

    - name: password
      prompt: What is your password?

  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: 'Logging in as {{ username }}'
      vars:
        username: task_level
