---
- hosts: all
  become: true

  vars_files:
    - "{{ ansible_facts['distribution'] }}.yaml"

  tasks:
    - name: Installing Apache2 webserver
      ansible.builtin.apt:
        name: "{{ http_package }}"
        state: present
        update_cache: true

    - name: Copying virtual host configuration
      ansible.builtin.copy:
        src: v_hosts.conf
        dest: "{{ config_file }}"
        mode: 0644
      notify: Restarted Apache2

    - name: Copying webpage - index.html
      ansible.builtin.copy:
        src: "index.{{ ansible_facts['distribution'] }}.html"
        dest: "{{ webpage }}"
        mode: 0444

  handlers:
    - name: Restarted Apache2
      ansible.builtin.service:
        name: apache2
        state: restarted
