---
- hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Simple loops
      ansible.builtin.debug:
        msg: "Elements --> {{ item }}"
      loop:
        - list_element1
        - list_element2
        - list_element3

    - name: file creation
      ansible.builtin.copy:
        dest: "/tmp/{{ item }}"
        content: "{{ item }} content"
        mode: 0666
      loop: "{{ ['file1', ['new_file1', 'new_file2'], 'hello.py'] | flatten(1) }}"

    - name: Add several users
      ansible.builtin.user:
        name: "{{ item }}"
        state: present
      loop:
        - testuser1
        - testuser2

    # - name: Tracking progress
    #   ansible.builtin.debug:
    #     msg: "Loop index {{ idx }} and item {{ item }}"
    #   loop:
    #     - file1
    #     - file2
    #     - file3
    #     - file4
    #   loop_control:
    #     index_var: idx
