---
- hosts: all
  gather_facts: false

  vars:
    greetings: Hello
    must: false
    myvar:
      skills:
        - ansible
        - terraform
    lists:
      - 11
      - 123
      - 11
      - 234

    variable: hi


  tasks:
    - name: Rendering template
      ansible.builtin.template:
        src: templates/generic.j2
        dest: /tmp/rendered
        mode: 0644
