---
- name: Ansible - Jinja2 examples
  hosts: all
  become: true
  
  vars:
    greetings: Hello
    must: false
    myvar:
      skills:
        - ansible
        - terraform
    lists:
      - 11
      - 123
      - 11
      - 234

    variable: hi


  tasks:
    - name: Rendering template
      ansible.builtin.template:
        src: templates/generic.j2
        dest: /tmp/rendered
        mode: "0644"

    - name: Copying /etc/hosts file
      ansible.builtin.template:
        src: templates/hosts.j2
        dest: /etc/hosts.dummy
        mode: "0644"
