---
- name: Installing apache webserver
  ansible.builtin.apt:
    name: apache2
    state: "{{ state }}"
    update_cache: true
  when: ansible_facts['distribution'] == 'Ubuntu'
  changed_when: true
  notify: Restart apache2

- name: Installing apache webserver
  ansible.builtin.yum:
    name: httpd
    state: present
  when: ansible_facts['distribution'] == 'CentOS'
  notify: Restart httpd - CentOS
