---
- name: Restart apache2
  ansible.builtin.service:
    name: apache2
    state: restarted

- name: Restart httpd - CentOS
  ansible.builtin.service:
    name: httpd
    state: restarted
  when: ansible_facts['distribution'] == 'CentOS'
