- name: Copying template files
  ansible.builtin.template:
    src: demo-template.j2
    dest: /tmp/demo-template-pasted
    mode: 0644

- name: Copying normal files
  ansible.builtin.copy:
    src: demo-file.txt
    dest: /tmp/demo-file.txt.copied
    mode: 0644
