---
- hosts: all
  become: true

  handlers:
    - name: Restart service
      ansible.builtin.import_tasks: handlers.yaml

  tasks:
    - name: Static task import
      ansible.builtin.import_tasks: apache2.yaml
      vars:
        state: present
